# For a simple Aurum setup, install Docker Compose
# <https://docs.docker.com/compose/install/> and run these commands:
#
# 1. docker-compose up -d elasticsearch
#     Brings up an elasticsearch instance using the data located at data/elasticsearch. This data persists even if you destroy and recreate the elasticsearch Docker container.
# 2*. docker-compose build profiler
# 2. docker-compose up profiler
#     Runs the ddprofiler with the CSVs located in data/csvs. Writes to the above elasticsearch container.
# 3*. docker-compose build nbc
# 3*. docker-compose run --rm -T nbc
# 3. docker-compose up -d neodb
#    Run the neo4j instance,user='neo4j',password='aurum'
# 4. docker-compose up nbc
#     Runs networkbuildercoordinator.py with the above elasticsearch and saves its files to data/pickles.
# 5. docker-compose up notebook
#     Runs a Jupyter notebook with Aurum libraries and the above pickles from data/pickles.
# 6. docker-compose up frontend
#     Runs the web frontend and API on http://localhost:3000 and http://localhost:5000 respectively. Uses pickles from data/pickles.

version: '3'

networks:
  aurum_net:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      aurum_net:
        aliases:
          - elasticsearch

  profiler:
    depends_on:
      - elasticsearch
    image: aurum/ddprofiler:0.1
    build:
      context: .
      dockerfile: docker/Dockerfile-ddprofiler
    volumes:
      - ./data:/data
    command: " --store.server elasticsearch --sources /data/mitdwhdata.yml"  # "<profiler args here>"
    networks:
      aurum_net:
        aliases:
          - profiler

  nbc:
    depends_on:
      - elasticsearch
    image: aurum/networkbuildercoordinator:0.1
    build:
      context: .
      dockerfile: docker/Dockerfile-networkbuildercoordinator
    volumes:
      - ./data/models:/output
    networks:
      aurum_net:
        aliases:
          - nbc

  notebook:
    depends_on:
      - elasticsearch
    image: aurum/notebook
    build:
      context: .
      dockerfile: docker/Dockerfile-jupyter-notebook
    volumes:
      - ./data/models:/data/models
    ports:
      - 8888:8888
    networks:
      aurum_net:
        aliases:
          - notebook

#  frontend:
#    depends_on:
#      - elasticsearch
#    image: aurum/frontend
#    build:
#      context: .
#      dockerfile: docker/Dockerfile-ui
#    volumes:
#      - ./data/models:/aurum/data/models
#    ports:
#      - 3000:3000
#      - 5000:5000
#    networks:
#      aurum_net:
#        aliases:
#          - frontend


