# ddprofiler
FROM openjdk:8

COPY . /aurum

#RUN cd /aurum/ddprofiler && ./gradlew clean fatJar
RUN cd /aurum/ddprofiler && bash build.sh

WORKDIR /aurum/ddprofiler

ENTRYPOINT ["/bin/bash", "/aurum/ddprofiler/run.sh", "${*}"]
